### PR TITLE
#164198466: opt in and out of notifications

### PR DESCRIPTION
**Pull request by Dsalz**
#### What does this PR do?
- It enables users to opt in and out of notifications

#### Description of Task to be completed?
- Create reusable profile card component
- Create settings page
- Create notifications tab
- Style components
- Enable users to opt in and out of the two types of notifications
- Create action creators for updating profile notification settings
- Test components and actions to be dispatched by them

#### How should this be manually tested?
1. Clone this branch.
2. Run `cd artemis-ah-frontend`
3. Run `npm install` to install the dependencies.
4. Run `npm test` to run the tests.

#### What are the relevant pivotal tracker stories?
[#164198466](https://pivotaltracker.com/story/show/164198466)

#### Screenshots (if appropriate)
Screenshot 2019-04-25 at 8 41 48 AM
Screenshot 2019-04-25 at 8 42 29 AM

### CODE REVIEW

**Review by adaezeodurukwe — COMMENTED** [review]
LGTM

**Review by Chrismarcel — COMMENTED** [review]
LGTM

**Review by shaolinmkz — COMMENTED** [review]
Reviewed

**Review by uniqueayo1988 — COMMENTED** [review]
Reviewed.
LGTM

**Review by andela-gike — APPROVED** [review]

**Pull request merged**
