### PR TITLE
#164198464 Feature to follow and unfollow user

### PR DESCRIPTION
**Pull request by danprocoder**
#### What does this PR do?
Feature to follow and unfollow user

#### Description of Task to be completed?
- Created feature to toggle follow/unfollow action.
- Correct number of articles shown in profile page.
- Wrote tests for follow/unfollow feature.

#### How should this be manually tested?
1. Clone this branch.
2. Run `cd artemis-ah-frontend`
3. Run `npm install` to install the dependencies.
4. Run `npm test` to run the tests.

#### What are the relevant pivotal tracker stories?
[#164198464](https://pivotaltracker.com/story/show/164198464)

### CODE REVIEW

**Review by adaezeodurukwe — COMMENTED** [review]
Reviewed

**Review by Dsalz — COMMENTED** [review]
Reviewed

**Review by shaolinmkz — COMMENTED** [review]
LGTM

**Review by Chrismarcel — COMMENTED** [review]
LGTM

**Review by uniqueayo1988 — COMMENTED** [review]
Reviewed.
LGTM

**Review by andela-gike — APPROVED** [review]

**Pull request merged**
