### PR TITLE
#165310082 Create explore page

### PR DESCRIPTION
**Pull request by adaezeodurukwe**
#### What does this PR do?
Create explore page

#### Description of Task to be completed?
* Create Explore view 
* Test Explore view

#### How should this be manually tested?
1. Clone this branch.
2. Run `cd artemis-ah-frontend`
3. Run `npm install` to install the dependencies.
4. Run `npm test` to run the tests.

#### What are the relevant pivotal tracker stories?
[#165310082](https://pivotaltracker.com/story/show/165310082)

#### Screenshots (if appropriate)
Screenshot 2019-04-18 at 6 19 44 PM
Screenshot 2019-04-18 at 6 48 36 PM

### CODE REVIEW

**Review by Chrismarcel — COMMENTED** [review]
LGTM

**Review by Dsalz — COMMENTED** [review]
LGTM

**Review by uniqueayo1988 — COMMENTED** [review]
Reviewed.
LGTM

**Review by danprocoder — COMMENTED** [review]
LGTM

**Review by andela-gike — APPROVED** [review]

**Pull request merged**
