### PR TITLE
#164198451 Implement signup user

### PR DESCRIPTION
**Pull request by adaezeodurukwe**
#### What does this PR do?
Implement user sign-up

#### Description of Task to be completed?
* Create and style Sign-up view/page
* Add sign-up actions
* Write tests for sign-up

#### How should this be manually tested?
1. Clone this branch.
2. Run `cd artemis-ah-frontend`
3. Run `npm install` to install the dependencies.
4. Run `npm test` to run the tests.

#### What are the relevant pivotal tracker stories?
[#164198451](https://pivotaltracker.com/story/show/164198451)

#### Screenshots (if appropriate)
Screenshot 2019-04-15 at 10 43 18 AM

Screenshot 2019-04-15 at 10 49 39 AM

Screenshot 2019-04-15 at 10 45 11 AM

#### Info
The close background on the mobile version has been fixed.

### CODE REVIEW

**Review by Dsalz — COMMENTED** [review]
LGTM

**Review by uniqueayo1988 — COMMENTED** [review]
Reviewed.
LGTM.

**Review by shaolinmkz — COMMENTED** [review]
LGTM

**Review by Chrismarcel — COMMENTED** [review]
Reviewed

**Review by andela-gike — APPROVED** [review]

**Pull request merged**
