### PR TITLE
#164198469 feature to add article to bookmark and remove an article from bookmark

### PR DESCRIPTION
**Pull request by danprocoder**
#### What does this PR do?
Add feature to add an article to bookmark and remove an article from bookmark.

#### Description of Task to be completed?
- Create feature to add an article to bookmark and remove an article from bookmark.
- Write tests for bookmark toggle feature.

#### How should this be manually tested?
1. Clone this branch.
2. Run `cd artemis-ah-frontend`
3. Run `npm install` to install the dependencies.
4. Run `npm test` to run the tests.

#### What are the relevant pivotal tracker stories?
[#164198469](https://pivotaltracker.com/story/show/164198469)

### CODE REVIEW

**Review by shaolinmkz — COMMENTED** [review]
Reviewed

**Review by Chrismarcel — COMMENTED** [review]
LGTM

**Review by uniqueayo1988 — COMMENTED** [review]
Reviewed.
LGTM

**Review by Dsalz — COMMENTED** [review]
Reviewed

**Review by adaezeodurukwe — COMMENTED** [review]
LGTM

**Review by andela-gike — APPROVED** [review]

**Pull request merged**
