### PR TITLE
#165762413 Fix bookmark toggle button bug

### PR DESCRIPTION
**Pull request by danprocoder**
#### What does this PR do?
Fix bookmark toggle button bug

#### Description of Task to be completed?
Bookmark button now shows "add to bookmark" if the article is not bookmarked and "remove from bookmark" if the article is bookmarked.

#### How should this be manually tested?
1. Clone this branch.
2. Run `cd artemis-ah-frontend`
3. Run `npm install` to install the dependencies.
4. Run `npm test` to run the tests.

#### What are the relevant pivotal tracker stories?
[#165762413](https://pivotaltracker.com/story/show/165762413)

### CODE REVIEW

**Review by adaezeodurukwe — COMMENTED** [review]
Reviewed

**Review by Chrismarcel — COMMENTED** [review]
Reviewed, LGTM

**Review by uniqueayo1988 — COMMENTED** [review]
Reviewed.

**Review by Dsalz — COMMENTED** [review]
Reviewed

**Review by andela-gike — APPROVED** [review]

**Pull request merged**
