### PR TITLE
##165119186 Search field

### PR DESCRIPTION
**Pull request by uniqueayo1988**
#### What does this PR do?
- This PR creates a search component

#### Description of Task to be completed?
- Create search field input 
- Create a search button to make input search field slide in
- Ensure input field is hidden when an event click is fired outside the input field
- Ensure enter key or search button searches for a keyword
- Style the input field
- Write tests

#### How should this be manually tested?
1. Clone this branch.
2. Run `cd artemis-ah-frontend`
3. Run `npm install` to install the dependencies.
4. Run `npm test` to run the tests.

#### What are the relevant pivotal tracker stories?
[##165119186](https://pivotaltracker.com/story/show/165119186)

#### Screenshots (if appropriate)
Search

### CODE REVIEW

**Review by Dsalz — COMMENTED** [review]
LGTM

**Review by Chrismarcel — COMMENTED** [review]
LGTM

**Review by adaezeodurukwe — COMMENTED** [review]
Reviewed

**Review by danprocoder — APPROVED** [review]

**Review by danprocoder — COMMENTED** [review]
LGTM

**Review by andela-gike — APPROVED** [review]

**Pull request merged**
