### PR TITLE
#164198454: user should be able to login

### PR DESCRIPTION
**Pull request by Dsalz**
#### What does this PR do?
- Adds login functionality to the platform

#### Description of Task to be completed?
- create login modal
- validate parameters passed by user
- post data to app API
- display API errors on the modal
- add SVG for social media icons
- modify reusable modal and button
- add click handler to login link on landing page
- add auth and user reducers
- add auth actions file
- Test everything
- refactor existing code to prefer destructuring

#### How should this be manually tested?
1. Clone this branch.
2. Run `cd artemis-ah-frontend`
3. Run `npm install` to install the dependencies.
4. Run `npm test` to run the tests.

#### What are the relevant pivotal tracker stories?
[#164198454]

#### Screenshots (if appropriate)
Screenshot 2019-04-09 at 10 38 05 AM
Screenshot 2019-04-09 at 10 36 49 AM
Screenshot 2019-04-09 at 10 36 26 AM
Screenshot 2019-04-09 at 12 48 52 PM

### CODE REVIEW

**Review by shaolinmkz — COMMENTED** [review]
Nice!. Please add a screenshot of the mobile view.

**Review by Chrismarcel — COMMENTED** [review]
Reviewed

**Review by shaolinmkz — COMMENTED** [review]
LGTM

**Review by adaezeodurukwe — COMMENTED** [review]
LGTM

**Review by andela-gike — APPROVED** [review]

**Pull request merged**
