### PR TITLE
#165635432: refactor update profile & new user onboarding

### PR DESCRIPTION
**Pull request by Dsalz**
#### What does this PR do?
- Refactor updating user's profile
- Add onboarding for new users

#### Description of Task to be completed?
- Enable users update their username
- Update store and storage with new information
- Add check and onboard new users logging in with social media
- Test action creators, reducers and components used to achieve functionality

#### How should this be manually tested?
1. Clone this branch.
2. Run `cd artemis-ah-frontend`
3. Run `npm install` to install the dependencies.
4. Run `npm test` to run the tests.

#### What are the relevant pivotal tracker stories?
[#165635432](https://pivotaltracker.com/story/show/165635432)

#### Screenshots (if appropriate)
Screenshot 2019-05-03 at 12 32 43 AM
Screenshot 2019-05-03 at 12 33 19 AM

### CODE REVIEW

**Review by shaolinmkz — COMMENTED** [review]
Reviewed

**Review by adaezeodurukwe — COMMENTED** [review]
Reviewed

**Review by Chrismarcel — COMMENTED** [review]
Reviewed, LGTM

**Review by andela-gike — APPROVED** [review]

**Review by andela-gike — CHANGES_REQUESTED** [review]
your test is failing

**Review by andela-gike — APPROVED** [review]

**Pull request merged**
