### PR TITLE
#164198474: user should be able to like/unlike comment

### PR DESCRIPTION
**Pull request by Dsalz**
#### What does this PR do?
- Enable users like and unlike comments

#### Description of Task to be completed?
- modify comment component to like/unlike comments when the user is logged in
- create action creators for liking/unliking comment
- configure reducers to handle actions to be dispatched to achieve functionality
- test component, action creators and reducer

#### How should this be manually tested?
1. Clone this branch.
2. Run `cd artemis-ah-frontend`
3. Run `npm install` to install the dependencies.
4. Run `npm test` to run the tests.

#### What are the relevant pivotal tracker stories?
[#164198474](https://pivotaltracker.com/story/show/164198474)

#### Screenshots (if appropriate)
Trimmed-Like_Unlike-Comment-

### CODE REVIEW

**Review by shaolinmkz — COMMENTED** [review]
LGTM

**Review by Chrismarcel — COMMENTED** [review]
Reviewed, LGTM

**Review by adaezeodurukwe — COMMENTED** [review]
Reviewed

**Review by uniqueayo1988 — COMMENTED** [review]
Reviewed.
LGTM

**Review by andela-gike — APPROVED** [review]

**Pull request merged**
